services:

  db:
    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb

    ports:
      - "8821:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8822:80"
    depends_on:
      - db

volumes:
  mysql_data: